name: Pull Request

on:
  pull_request:

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm i


      - name: build
        run: npm run build

      - name: Test
        run: npm run test
